package com.example;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;

import java.util.List;

public class PopulateDatabase {
    public static void main(String[] args) {
        MongoClient mongoClient = new MongoClient("localhost", 27017);
        MongoDatabase database = mongoClient.getDatabase("language_learning");
        MongoCollection<Document> collection = database.getCollection("words");

        collection.insertMany(List.of(
            /* 
            new Document("word", "cat").append("translation", "кіт").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "dog").append("translation", "пес").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "apple").append("translation", "яблуко").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "run").append("translation", "бігти").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "tree").append("translation", "дерево").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "house").append("translation", "будинок").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "car").append("translation", "автомобіль").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "bike").append("translation", "велосипед").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "book").append("translation", "книга").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "sky").append("translation", "небо").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "computer").append("translation", "комп'ютер").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "phone").append("translation", "телефон").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "university").append("translation", "університет").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "library").append("translation", "бібліотека").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "station").append("translation", "станція").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "president").append("translation", "президент").append("level", "B2").append("difficultyLevel", 0),
            new Document("word", "government").append("translation", "уряд").append("level", "B2").append("difficultyLevel", 0),
            new Document("word", "economy").append("translation", "економіка").append("level", "B2").append("difficultyLevel", 0),
            new Document("word", "science").append("translation", "наука").append("level", "B2").append("difficultyLevel", 0),
            new Document("word", "technology").append("translation", "технологія").append("level", "B2").append("difficultyLevel", 0),
            new Document("word", "philosophy").append("translation", "філософія").append("level", "C1").append("difficultyLevel", 0),
            new Document("word", "psychology").append("translation", "психологія").append("level", "C1").append("difficultyLevel", 0),
            new Document("word", "literature").append("translation", "література").append("level", "C1").append("difficultyLevel", 0),
            new Document("word", "medicine").append("translation", "медицина").append("level", "C1").append("difficultyLevel", 0),
            new Document("word", "architecture").append("translation", "архітектура").append("level", "C1").append("difficultyLevel", 0),
            new Document("word", "quantum").append("translation", "квантовий").append("level", "C2").append("difficultyLevel", 0),
            new Document("word", "relativity").append("translation", "відносність").append("level", "C2").append("difficultyLevel", 0),
            new Document("word", "metaphysics").append("translation", "метафізика").append("level", "C2").append("difficultyLevel", 0),
            new Document("word", "epistemology").append("translation", "епістемологія").append("level", "C2").append("difficultyLevel", 0),
            new Document("word", "neuroscience").append("translation", "нейронаука").append("level", "C2").append("difficultyLevel", 0),
            */

            //нові слова а1
            new Document("word", "water").append("translation", "вода").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "sun").append("translation", "сонце").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "moon").append("translation", "місяць").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "star").append("translation", "зірка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "grass").append("translation", "трава").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "flower").append("translation", "квітка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "rain").append("translation", "дощ").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "snow").append("translation", "сніг").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "wind").append("translation", "вітер").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "storm").append("translation", "буря").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "beach").append("translation", "пляж").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "river").append("translation", "річка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "mountain").append("translation", "гора").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "forest").append("translation", "ліс").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "lake").append("translation", "озеро").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "ocean").append("translation", "океан").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "island").append("translation", "острів").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "field").append("translation", "поле").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "desert").append("translation", "пустеля").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "valley").append("translation", "долина").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "cave").append("translation", "печера").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "hill").append("translation", "пагорб").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "cliff").append("translation", "скеля").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "waterfall").append("translation", "водоспад").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "stream").append("translation", "струмок").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "pond").append("translation", "ставок").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "canal").append("translation", "канал").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "bridge").append("translation", "міст").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "road").append("translation", "дорога").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "path").append("translation", "стежка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "street").append("translation", "вулиця").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "city").append("translation", "місто").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "village").append("translation", "село").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "town").append("translation", "містечко").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "capital").append("translation", "столиця").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "country").append("translation", "країна").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "continent").append("translation", "континент").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "world").append("translation", "світ").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "earth").append("translation", "земля").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "planet").append("translation", "планета").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "space").append("translation", "космос").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "galaxy").append("translation", "галактика").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "universe").append("translation", "всесвіт").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "school").append("translation", "школа").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "teacher").append("translation", "вчитель").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "student").append("translation", "учень").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "classroom").append("translation", "клас").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "homework").append("translation", "домашнє завдання").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "exam").append("translation", "екзамен").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "lesson").append("translation", "урок").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "subject").append("translation", "предмет").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "textbook").append("translation", "підручник").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "pen").append("translation", "ручка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "pencil").append("translation", "олівець").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "paper").append("translation", "папір").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "notebook").append("translation", "зошит").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "backpack").append("translation", "рюкзак").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "desk").append("translation", "парта").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "chair").append("translation", "стілець").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "board").append("translation", "дошка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "bookstore").append("translation", "книжковий магазин").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "library").append("translation", "бібліотека").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "cafeteria").append("translation", "їдальня").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "playground").append("translation", "ігровий майданчик").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "gym").append("translation", "спортивний зал").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "office").append("translation", "офіс").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "principal").append("translation", "директор").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "nurse").append("translation", "медсестра").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "janitor").append("translation", "двірник").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "bell").append("translation", "дзвінок").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "holiday").append("translation", "свято").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "celebration").append("translation", "святкування").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "party").append("translation", "вечірка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "gift").append("translation", "подарунок").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "card").append("translation", "листівка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "balloon").append("translation", "кулька").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "cake").append("translation", "торт").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "candle").append("translation", "свічка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "music").append("translation", "музика").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "dance").append("translation", "танець").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "song").append("translation", "пісня").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "band").append("translation", "гурт").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "singer").append("translation", "співак").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "instrument").append("translation", "інструмент").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "piano").append("translation", "фортепіано").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "guitar").append("translation", "гітара").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "drum").append("translation", "барабан").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "violin").append("translation", "скрипка").append("level", "A1").append("difficultyLevel", 0),
            new Document("word", "flute").append("translation", "флейта").append("level", "A1").append("difficultyLevel", 0),

            //нові слова а2
            new Document("word", "library").append("translation", "бібліотека").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "restaurant").append("translation", "ресторан").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "market").append("translation", "ринок").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "hospital").append("translation", "лікарня").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "pharmacy").append("translation", "аптека").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "station").append("translation", "станція").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "airport").append("translation", "аеропорт").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "bank").append("translation", "банк").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "post office").append("translation", "поштове відділення").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "shop").append("translation", "магазин").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mall").append("translation", "торговий центр").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "supermarket").append("translation", "супермаркет").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "store").append("translation", "магазин").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "cinema").append("translation", "кінотеатр").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "theater").append("translation", "театр").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "museum").append("translation", "музей").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "park").append("translation", "парк").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "zoo").append("translation", "зоопарк").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "amusement park").append("translation", "парк розваг").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "aquarium").append("translation", "акваріум").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "beach").append("translation", "пляж").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "forest").append("translation", "ліс").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mountain").append("translation", "гора").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "desert").append("translation", "пустеля").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "island").append("translation", "острів").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "river").append("translation", "річка").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "lake").append("translation", "озеро").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "waterfall").append("translation", "водоспад").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "valley").append("translation", "долина").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "cave").append("translation", "печера").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "hill").append("translation", "пагорб").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "cliff").append("translation", "скеля").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "field").append("translation", "поле").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "meadow").append("translation", "лука").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "grass").append("translation", "трава").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "flower").append("translation", "квітка").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "tree").append("translation", "дерево").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "bush").append("translation", "кущ").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "plant").append("translation", "рослина").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "animal").append("translation", "тварина").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "insect").append("translation", "комаха").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "bird").append("translation", "птах").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "fish").append("translation", "риба").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "reptile").append("translation", "плазуни").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mammal").append("translation", "ссавець").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "amphibian").append("translation", "земноводні").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "weather").append("translation", "погода").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "climate").append("translation", "клімат").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "temperature").append("translation", "температура").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "season").append("translation", "сезон").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "spring").append("translation", "весна").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "summer").append("translation", "літо").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "autumn").append("translation", "осінь").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "winter").append("translation", "зима").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "rain").append("translation", "дощ").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "snow").append("translation", "сніг").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "hail").append("translation", "град").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "sleet").append("translation", "мокрий сніг").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "fog").append("translation", "туман").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mist").append("translation", "імла").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "cloud").append("translation", "хмара").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "wind").append("translation", "вітер").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "breeze").append("translation", "бриз").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "storm").append("translation", "буря").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "hurricane").append("translation", "ураган").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "tornado").append("translation", "торнадо").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "thunder").append("translation", "грім").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "lightning").append("translation", "блискавка").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "sun").append("translation", "сонце").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "moon").append("translation", "місяць").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "star").append("translation", "зірка").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "planet").append("translation", "планета").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "galaxy").append("translation", "галактика").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "universe").append("translation", "всесвіт").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "space").append("translation", "космос").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "astronaut").append("translation", "астронавт").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "rocket").append("translation", "ракета").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "satellite").append("translation", "супутник").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "telescope").append("translation", "телескоп").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "comet").append("translation", "комета").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "meteor").append("translation", "метеорит").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "asteroid").append("translation", "астероїд").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "black hole").append("translation", "чорна діра").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "nebula").append("translation", "туманність").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "cosmos").append("translation", "космос").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "astronomy").append("translation", "астрономія").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "astrology").append("translation", "астрологія").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "constellation").append("translation", "сузір'я").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "eclipse").append("translation", "затемнення").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "atmosphere").append("translation", "атмосфера").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "orbit").append("translation", "орбіта").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "gravity").append("translation", "гравітація").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mass").append("translation", "маса").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "weight").append("translation", "вага").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "density").append("translation", "щільність").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "volume").append("translation", "обсяг").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "pressure").append("translation", "тиск").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "force").append("translation", "сила").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "velocity").append("translation", "швидкість").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "acceleration").append("translation", "прискорення").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "momentum").append("translation", "імпульс").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "energy").append("translation", "енергія").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "work").append("translation", "робота").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "power").append("translation", "потужність").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "current").append("translation", "струм").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "voltage").append("translation", "напруга").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "resistance").append("translation", "опір").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "circuit").append("translation", "коло").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "frequency").append("translation", "частота").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "wavelength").append("translation", "довжина хвилі").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "amplitude").append("translation", "амплітуда").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "wave").append("translation", "хвиля").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "light").append("translation", "світло").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "sound").append("translation", "звук").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "reflection").append("translation", "відображення").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "refraction").append("translation", "переломлення").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "absorption").append("translation", "поглинання").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "transmission").append("translation", "передача").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "medium").append("translation", "середовище").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "particle").append("translation", "частинка").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "atom").append("translation", "атом").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "molecule").append("translation", "молекула").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "element").append("translation", "елемент").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "compound").append("translation", "сполука").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mixture").append("translation", "суміш").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "solution").append("translation", "розчин").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "concentration").append("translation", "концентрація").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "acid").append("translation", "кислота").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "base").append("translation", "основа").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "salt").append("translation", "сіль").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "reaction").append("translation", "реакція").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "catalyst").append("translation", "каталізатор").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "enzyme").append("translation", "фермент").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "substrate").append("translation", "субстрат").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "product").append("translation", "продукт").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "cell").append("translation", "клітина").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "organ").append("translation", "орган").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "tissue").append("translation", "тканина").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "organism").append("translation", "організм").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "species").append("translation", "вид").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "ecosystem").append("translation", "екосистема").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "environment").append("translation", "середовище").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "habitat").append("translation", "середовище існування").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "adaptation").append("translation", "адаптація").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "evolution").append("translation", "еволюція").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "gene").append("translation", "ген").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "chromosome").append("translation", "хромосома").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "DNA").append("translation", "ДНК").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "RNA").append("translation", "РНК").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mutation").append("translation", "мутація").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "protein").append("translation", "білок").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "carbohydrate").append("translation", "вуглевод").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "lipid").append("translation", "ліпід").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "vitamin").append("translation", "вітамін").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "mineral").append("translation", "мінералія").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "metabolism").append("translation", "метаболізм").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "respiration").append("translation", "дихання").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "digestion").append("translation", "травлення").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "circulation").append("translation", "циркуляція").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "reproduction").append("translation", "розмноження").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "immune").append("translation", "імунітет").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "nervous").append("translation", "нервовий").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "endocrine").append("translation", "ендокринний").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "skeletal").append("translation", "скелетний").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "muscular").append("translation", "м'язовий").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "excretory").append("translation", "видільний").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "integumentary").append("translation", "покривний").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "skeletal system").append("translation", "скелетна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "muscular system").append("translation", "м'язова система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "nervous system").append("translation", "нервова система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "circulatory system").append("translation", "кровоносна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "digestive system").append("translation", "травна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "respiratory system").append("translation", "дихальна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "reproductive system").append("translation", "репродуктивна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "urinary system").append("translation", "сечовидільна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "immune system").append("translation", "імунна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "endocrine system").append("translation", "ендокринна система").append("level", "A2").append("difficultyLevel", 0),
            new Document("word", "integumentary system").append("translation", "покривна система").append("level", "A2").append("difficultyLevel", 0),

            //нові в1
            new Document("word", "bacteria").append("translation", "бактерії").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "virus").append("translation", "вірус").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "fungus").append("translation", "грибок").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "algae").append("translation", "водорості").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "parasite").append("translation", "паразит").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "antibiotic").append("translation", "антибіотик").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "vaccine").append("translation", "вакцина").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "antibody").append("translation", "антитіло").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "symptom").append("translation", "симптом").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "diagnosis").append("translation", "діагноз").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "treatment").append("translation", "лікування").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "therapy").append("translation", "терапія").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "surgery").append("translation", "операція").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "medicine").append("translation", "медикамент").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "pharmacy").append("translation", "аптека").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "patient").append("translation", "пацієнт").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "doctor").append("translation", "лікар").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "nurse").append("translation", "медсестра").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "hospital").append("translation", "лікарня").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "clinic").append("translation", "клініка").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "health").append("translation", "здоров'я").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "disease").append("translation", "хвороба").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "infection").append("translation", "інфекція").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "virus").append("translation", "вірус").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "bacteria").append("translation", "бактерія").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "cancer").append("translation", "рак").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "diabetes").append("translation", "діабет").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "heart").append("translation", "серце").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "brain").append("translation", "мозок").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "liver").append("translation", "печінка").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "kidney").append("translation", "нирка").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "lung").append("translation", "легеня").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "intestine").append("translation", "кишка").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "stomach").append("translation", "шлунок").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "bladder").append("translation", "сечовий міхур").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "pancreas").append("translation", "підшлункова залоза").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "spleen").append("translation", "селезінка").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "bone").append("translation", "кістка").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "muscle").append("translation", "м'яз").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "nerve").append("translation", "нерв").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "vein").append("translation", "вена").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "artery").append("translation", "артерія").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "skin").append("translation", "шкіра").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "cell").append("translation", "клітина").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "tissue").append("translation", "тканина").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "organ").append("translation", "орган").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "organism").append("translation", "організм").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "species").append("translation", "вид").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "ecosystem").append("translation", "екосистема").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "environment").append("translation", "середовище").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "habitat").append("translation", "середовище існування").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "adaptation").append("translation", "адаптація").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "evolution").append("translation", "еволюція").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "gene").append("translation", "ген").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "chromosome").append("translation", "хромосома").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "DNA").append("translation", "ДНК").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "RNA").append("translation", "РНК").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "mutation").append("translation", "мутація").append("level", "B1").append("difficultyLevel", 0),
            new Document("word", "protein").append("translation", "білок").append("level", "B1").append("difficultyLevel", 0)


        
        
            ));

        mongoClient.close();
    }
}
